<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://controller.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://controller.com" xmlns:intf="http://controller.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://controller.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getFunction">
    <complexType/>
   </element>
   <element name="getFunctionResponse">
    <complexType>
     <sequence>
      <element name="getFunctionReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getFunctionResponse">

      <wsdl:part element="impl:getFunctionResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getFunctionRequest">

      <wsdl:part element="impl:getFunction" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="First">

      <wsdl:operation name="getFunction">

         <wsdl:input message="impl:getFunctionRequest" name="getFunctionRequest">

       </wsdl:input>

         <wsdl:output message="impl:getFunctionResponse" name="getFunctionResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="FirstSoapBinding" type="impl:First">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getFunction">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getFunctionRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getFunctionResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="FirstService">

      <wsdl:port binding="impl:FirstSoapBinding" name="First">

         <wsdlsoap:address location="http://localhost:8080/restMvc/services/First"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
